//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImputacionHoras.Presentation.Forms {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinFormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImputacionHoras.Presentation.Forms.WinFormResources", typeof(WinFormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llamadas a la API realizadas:.
        /// </summary>
        public static string ApiCalls {
            get {
                return ResourceManager.GetString("ApiCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imporatción de Assets correcta.
        /// </summary>
        public static string AssetsImport {
            get {
                return ResourceManager.GetString("AssetsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billings calculados correctamente.
        /// </summary>
        public static string BillingCalculate {
            get {
                return ResourceManager.GetString("BillingCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imporatción de Contracts correcta.
        /// </summary>
        public static string ContractsImport {
            get {
                return ResourceManager.GetString("ContractsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportación finalizada..
        /// </summary>
        public static string ExportEnded {
            get {
                return ResourceManager.GetString("ExportEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imporatción de Imputaciones correcta.
        /// </summary>
        public static string ImputacionesImport {
            get {
                return ResourceManager.GetString("ImputacionesImport", resourceCulture);
            }
        }
    }
}
